### ISSUE TITLE
Configure lint-staged and husky for components

### ISSUE THREAD

**Issue by JRobsonJr** [vtex/andromedocs#14]
**Is your feature request related to a problem? Please describe.**
Our code style quality isn't being ensured when sending commits. 

**Describe the solution you'd like**
We can add a configuration of `lint-staged` + `husky` to create Git to help enforce the code style.

**Describe alternatives you've considered**
1. Add lint-staged and husky as dev dependencies (`yarn add -D husky lint-staged`);
2. Add a format script to package.json to run prettier: (`"format": "prettier --write \"**/*.{ts,js,json,tsx}\""`); 
3. Add husky and lint-staged configs to package.json:
```json
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{ts,js,tsx,jsx}": [
      "eslint --fix",
      "prettier --write"
    ],
    "*.json": [
      "prettier --write"
    ]
  }
```

**Comment by thayannevls** [comment]
Also, it would be good to add different scripts for each package. Example:

`yarn lint:components`
