### ISSUE TITLE
Config Components packages

### ISSUE THREAD

**Issue by thayannevls** [vtex/andromedocs#4]
**Is your feature request related to a problem? Please describe.**
The andromedocs will have some components to help document their design systems. So we need a package that contains these components.

**Describe the solution you'd like**
...

**Describe alternatives you've considered**
- `yarn init`
- https://github.com/vtex/create-react-library

**Comment by LeandraOliveiraS** [comment]
Hello :smile: @thayannevls, @JRobsonJr and @JGuilhermeCoelho a few minutes ago I added the configuration of the component package. :rocket:
